# Intercoder reliability sample

Merging coder 1, coder 2, LLM coder and the model's own topic assignments for the 200 sample reviews from 2.7.

In [1]:
import pandas as pd
from sklearn.metrics import cohen_kappa_score

# Coder paths
CODER1 = "data/coder_1.csv"
CODER2 = "data/coder_2.csv"
CODERLLM = "data/coder_llm.csv"

In [2]:
sample = pd.read_csv("data/coding_sample_200.csv")
sample = sample.drop(columns=["topic_number"])
sample.head()

,review_id,year,season,designer,author,city,date,review
0,45,2000,Spring,Ellen Tracy,Armand Limnander,New York,14-Sep-99,"There's a fresh, younger look to my collection..."
1,152,2000,Fall,Tristan Webber,Plum Sykes,London,17-Feb-00,Tristan Webber is London's king of leather a f...
2,144,2000,Fall,Cerruti,Hamish Bowles,Paris,2-Mar-00,Peter Speliopoulos takes the Milanese route fo...
3,113,2000,Fall,Missoni,Armand Limnander,Milan,22-Feb-00,It's a good fashion moment for Missoni. Prints...
4,76,2000,Spring,Prada,Armand Limnander,Milan,27-Sep-99,Miuccia Prada showed today what is certain to ...

In [3]:
model_df = pd.read_csv("outputs_rlda_codebook/codebook_dominant_topic_assignments.csv")
model_df = model_df[["doc_id", "dominant_topic"]].rename(columns={"doc_id": "review_id", "dominant_topic": "model_assignment"})

sample = sample.merge(model_df, on="review_id", how="left")
sample.head()

,review_id,year,season,designer,author,city,date,review,model_assignment
0,45,2000,Spring,Ellen Tracy,Armand Limnander,New York,14-Sep-99,"There's a fresh, younger look to my collection...",1
1,152,2000,Fall,Tristan Webber,Plum Sykes,London,17-Feb-00,Tristan Webber is London's king of leather a f...,4
2,144,2000,Fall,Cerruti,Hamish Bowles,Paris,2-Mar-00,Peter Speliopoulos takes the Milanese route fo...,3
3,113,2000,Fall,Missoni,Armand Limnander,Milan,22-Feb-00,It's a good fashion moment for Missoni. Prints...,1
4,76,2000,Spring,Prada,Armand Limnander,Milan,27-Sep-99,Miuccia Prada showed today what is certain to ...,1

In [4]:
coder1_df = pd.read_csv(CODER1)
coder1_df = coder1_df[["review_id", "topic_number"]].rename(columns={"topic_number": "coder_1"})
coder1_df["coder_1"] = coder1_df["coder_1"].astype("Int64")

sample = sample.merge(coder1_df, on="review_id", how="left")
sample.head()

,review_id,year,season,designer,author,city,date,review,model_assignment,coder_1
0,45,2000,Spring,Ellen Tracy,Armand Limnander,New York,14-Sep-99,"There's a fresh, younger look to my collection...",1,9
1,152,2000,Fall,Tristan Webber,Plum Sykes,London,17-Feb-00,Tristan Webber is London's king of leather a f...,4,0
2,144,2000,Fall,Cerruti,Hamish Bowles,Paris,2-Mar-00,Peter Speliopoulos takes the Milanese route fo...,3,3
3,113,2000,Fall,Missoni,Armand Limnander,Milan,22-Feb-00,It's a good fashion moment for Missoni. Prints...,1,2
4,76,2000,Spring,Prada,Armand Limnander,Milan,27-Sep-99,Miuccia Prada showed today what is certain to ...,1,4

In [5]:
coder2_df = pd.read_csv(CODER2)
coder2_df = coder2_df[["review_id", "topic_number"]].rename(columns={"topic_number": "coder_2"})
coder2_df["coder_2"] = coder2_df["coder_2"].astype("Int64")


sample = sample.merge(coder2_df, on="review_id", how="left")
sample.head()

,review_id,year,season,designer,author,city,date,review,model_assignment,coder_1,coder_2
0,45,2000,Spring,Ellen Tracy,Armand Limnander,New York,14-Sep-99,"There's a fresh, younger look to my collection...",1,9,1
1,152,2000,Fall,Tristan Webber,Plum Sykes,London,17-Feb-00,Tristan Webber is London's king of leather a f...,4,0,0
2,144,2000,Fall,Cerruti,Hamish Bowles,Paris,2-Mar-00,Peter Speliopoulos takes the Milanese route fo...,3,3,4
3,113,2000,Fall,Missoni,Armand Limnander,Milan,22-Feb-00,It's a good fashion moment for Missoni. Prints...,1,2,2
4,76,2000,Spring,Prada,Armand Limnander,Milan,27-Sep-99,Miuccia Prada showed today what is certain to ...,1,4,4

In [6]:
llm_df = pd.read_csv(CODERLLM)
llm_df = llm_df[["review_id", "topic_number"]].rename(columns={"topic_number": "llm_coder"})

sample = sample.merge(llm_df, on="review_id", how="left")
sample.head()

,review_id,year,season,designer,author,city,date,review,model_assignment,coder_1,coder_2,llm_coder
0,45,2000,Spring,Ellen Tracy,Armand Limnander,New York,14-Sep-99,"There's a fresh, younger look to my collection...",1,9,1,9
1,152,2000,Fall,Tristan Webber,Plum Sykes,London,17-Feb-00,Tristan Webber is London's king of leather a f...,4,0,0,0
2,144,2000,Fall,Cerruti,Hamish Bowles,Paris,2-Mar-00,Peter Speliopoulos takes the Milanese route fo...,3,3,4,3
3,113,2000,Fall,Missoni,Armand Limnander,Milan,22-Feb-00,It's a good fashion moment for Missoni. Prints...,1,2,2,2
4,76,2000,Spring,Prada,Armand Limnander,Milan,27-Sep-99,Miuccia Prada showed today what is certain to ...,1,4,4,2

In [7]:
sample = sample[["review_id", "year", "season", "designer", "author", "city", "date", "review",
                  "coder_1", "coder_2", "llm_coder", "model_assignment"]]

sample.to_csv("data/coding_sample_200_intercoder.csv", index=False)
print(len(sample))
sample.head()

200

,review_id,year,season,designer,author,city,date,review,coder_1,coder_2,llm_coder,model_assignment
0,45,2000,Spring,Ellen Tracy,Armand Limnander,New York,14-Sep-99,"There's a fresh, younger look to my collection...",9,1,9,1
1,152,2000,Fall,Tristan Webber,Plum Sykes,London,17-Feb-00,Tristan Webber is London's king of leather a f...,0,0,0,4
2,144,2000,Fall,Cerruti,Hamish Bowles,Paris,2-Mar-00,Peter Speliopoulos takes the Milanese route fo...,3,4,3,3
3,113,2000,Fall,Missoni,Armand Limnander,Milan,22-Feb-00,It's a good fashion moment for Missoni. Prints...,2,2,2,1
4,76,2000,Spring,Prada,Armand Limnander,Milan,27-Sep-99,Miuccia Prada showed today what is certain to ...,4,4,2,1

In [8]:
raters = ["coder_1", "coder_2", "llm_coder", "model_assignment"]

for i in range(len(raters)):
    for j in range(i + 1, len(raters)):
        r1 = raters[i]
        r2 = raters[j]
        pair = sample[[r1, r2]].dropna()
        kappa = cohen_kappa_score(pair[r1], pair[r2])
        print(r1, "vs", r2, "-> kappa =", round(kappa, 3), "(n =", len(pair), ")")

coder_1 vs coder_2 -> kappa = 0.66 (n = 200 )
coder_1 vs llm_coder -> kappa = 0.33 (n = 200 )
coder_1 vs model_assignment -> kappa = 0.077 (n = 200 )
coder_2 vs llm_coder -> kappa = 0.332 (n = 200 )
coder_2 vs model_assignment -> kappa = 0.056 (n = 200 )
llm_coder vs model_assignment -> kappa = 0.102 (n = 200 )